uav_names: ["uav1", "uav2", "uav3", "uav4", "uav5", "uav6"]

odometry_topic: "estimation_manager/odom_main"
intent_topic: "intent"

set_reference_timer:
  rate: 10 # [Hz]

diagnostics:
  rate: 0.5 # [Hz]
  odom_timeout: 1.0 # [s]

feedback:
  rate: 10 # [Hz]
  threshold: 0.1 #[m] 

odom_msg_max_latency: 1.0 # [s]

# control approach params
controlled_dimensions: 3

boid_constants:
  flocking: 15.0
  avoidance: 10.0
  velocity: 7.0
  waypoint: 9.0