#uav_names: ["uav9", "uav14", "uav16"]
#uav_names: ["uav16", "uav9"]
uav_names: ["uav11", "uav12"]

odometry_topic: "estimation_manager/odom_main"
reference_service_name: "control_manager/reference"
feedback_topic: "feedback"

file_path: "/home/traskos/ws_examples/src/swarm_controllers/data/"

set_reference_timer:
  rate: 20 # [Hz]
