simulation_rate: 100.0
dynamic:
  realtime_factor: 0.2
  collisions:
    crash: false
    enabled: false

frames:
  fcu:
    publish_tf: true

uav_names: [
  "uav1",
  "uav2",
  "uav3",
]

uav1:
  type: "x500"
  spawn:
    x: 10.0 #10
    y: 0.0 #0
    z: 2.0
    heading: 0.0

uav2:
  type: "x500"
  spawn:
    x: 7.66 #6.2348980185873355
    y: 6.42 #7.818314824680298
    z: 2.0
    heading: 0.0

uav3:
  type: "x500"
  spawn:
    x: 1.73 #-2.22520933956314
    y: 9.84 #9.7492791218
    z: 2.0
    heading: 0.0

individual_takeoff_platform:
  enabled: true
